### PR TITLE
IPOP Optical SDN use case

### PR DESCRIPTION
**Pull request by ubihgu**
IPOP 2020 showcase orchestrating AON SDN  optical controller

### CODE REVIEW

**Review by abr-ubiqube — CHANGES_REQUESTED** [review]
maybe rename **IPOP2020_showcase__Optical_E2E_automation_** to **IPOP2020_showcase_Optical_E2E_automation** ?

**Review by abr-ubiqube — COMMENTED** [review]
@ubihgu 
are you sure it's on the IPOP branch ? and the base branch should be 2.2.0GA I think

**Comment by ubihgu** [comment]
> are you sure it's on the IPOP branch ? and the base branch should be 2.2.0GA I think

IPOP branch had only the renaming of the WF so added chekpoint
should be merged into 2.2GA

**Review by abr-ubiqube — COMMENTED** [review]
maybe change the path to something like Checkpoint/Good_Better_Best or Good_Better_Best/Checkpoint ?

**Pull request merged**
