### PR TITLE
Updating the lib functions to use regex based deviceid instead of substr

### PR DESCRIPTION
**Pull request by nku-ubiqube**

### CODE REVIEW

**Comment by abr-ubiqube** [comment]
@nku-ubiqube , maybe a single centralized function would have been better? IN case we need to change the regex

**Comment by nku-ubiqube** [comment]
But in this PR, I have replace substr usage in all the places to extract the numeric part from the device id using sed, earlier we used sbstr to chop off the alphabets which might in some cases cause problems as we do not get device external reference in the api response of device creation. Hence in order to work with both the cases I added this code. We might not need to use this in future.

**Comment by abr-ubiqube** [comment]
yes, but if we don't need it in the future, we'll have to update the code everywhere, whereas if we have a function 

function get_id($ubi_id) {
  $device_id = preg_replace('/[A-Z]+/', '', $ubi_id);
  return $device_id;
}

it's much easier to maintain

**Comment by nku-ubiqube** [comment]
Creating a new PR

**Pull request closed without merging**
